%YAML:1.0



# Target Color
# all - 0
# red - 1
# blue - 2
Target.color: 0

brightness_threshold: 25
template_extend_ratio: 0.9
Gama: 10
#箭头
rect_min_area: 500
arrow_min_size: 6
rect_max_ratio: 5
mtach_step: 1		#旋转步距角
score_threshold: 0.6

#大小箭头
arrow_max_lenth: 70


# 枪口补偿
小跳蛙:
    distance_of_cam_fric.x: 0
    distance_of_cam_fric.y: 42.0
    distance_of_cam_fric.z: 102.0
    

小霸王:
    distance_of_cam_fric.x: 0
    distance_of_cam_fric.y: 57.0
    distance_of_cam_fric.z: 44.9

    imu_compensate.pitch  : 0.1
    imu_compensate.yaw    : -0.15

小汤圆:
    distance_of_cam_fric.x: 0
    distance_of_cam_fric.y: 57.0
    distance_of_cam_fric.z: 44.9
    distance_of_cam_spindle.x: 0
    distance_of_cam_spindle.y: 0
    distance_of_cam_spindle.z: 0

    imu_compensate.pitch  : 0
    imu_compensate.yaw    : 0

小王霸: 
    distance_of_cam_fric.x: 0
    distance_of_cam_fric.y: 42.0
    distance_of_cam_fric.z: 116.0
    
Ghost: 
    distance_of_cam_fric.x: 60.0
    distance_of_cam_fric.y: -30.9
    distance_of_cam_fric.z: 60.0
    

# 小彩石枪口补偿
小彩石上云台:
    distance_of_cam_fric.y: 46.1
    distance_of_cam_fric.z: 79.5

小彩石下云台:
    distance_of_cam_fric.y: -46.1
    distance_of_cam_fric.z: 79.5
